name: CADET-DG_evaluation_env
channels:
  - conda-forge
dependencies:
  - anaconda=custom
  - python=3.9.5
  - scipy=1.10.0
  - ipython=8.8.0
  - numpy=1.23.5
  - matplotlib=3.6.2
  - pandas=1.5.2
  - h5py=3.6.0
  - pytest=7.2.0
  - colorama=0.4.6
  - cadet # Note: To replicate the evaluation exactly, you need to build CADET-DG from source using the commit that is given in this repo.
  - pip
  - pip:
      - cadet-python
